server:
  port: 8085

spring:
  application:
    name: notification-service

  cloud:
    config:
      enabled: false

  mail:
    host: smtp.gmail.com
    port: 465
    username: health.sync.26@gmail.com
    password: qagixemjsbzblods

    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
