server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    config:
      enabled: false

jwt:
  secret: healthsyncsecretkeyhealthsyncsecretkey

eureka:
  client:
    enabled: false
