ALTER TABLE doctors ADD COLUMN stage VARCHAR(255);

INSERT INTO doctors (full_name, email, specialization, hospital, experience, phone, availability, stage) VALUES
('Dr. Ruwan Wijewardene', 'ruwan.wijewardene0@healthsync.com', 'Cardiology', 'National Hospital of Sri Lanka', 1, '+94-77-1000000', 'Mon-Wed, 9AM-3PM', 'INTERN'),
('Dr. Anura Perera', 'anura.perera1@healthsync.com', 'Pediatrics', 'Sri Jayewardenepura General Hospital', 4, '+94-71-1017923', 'Tue-Thu, 9AM-4PM', 'MO'),
('Dr. Sanduni Senanayake', 'sanduni.senanayake2@healthsync.com', 'Neurology', 'Lanka Hospitals', 7, '+94-76-1035846', 'Wed-Fri, 9AM-5PM', 'REGISTRAR'),
('Dr. Kasun Jayasundara', 'kasun.jayasundara3@healthsync.com', 'Dermatology', 'Durdans Hospital', 13, '+94-72-1053769', 'Thu-Mon, 9AM-3PM', 'CONSULTANT'),
('Dr. Nilmini Silva', 'nilmini.silva4@healthsync.com', 'General Medicine', 'Nawaloka Hospital', 1, '+94-70-1071692', 'Fri-Tue, 9AM-4PM', 'INTERN'),
('Dr. Priyantha Fernando', 'priyantha.fernando5@healthsync.com', 'Orthopedics', 'Asiri Surgical Hospital', 5, '+94-11-1089615', 'Mon-Wed, 9AM-5PM', 'MO'),
('Dr. Chaminda Herath', 'chaminda.herath6@healthsync.com', 'Ophthalmology', 'Colombo General Hospital', 6, '+94-77-1107538', 'Tue-Thu, 9AM-3PM', 'REGISTRAR'),
('Dr. Kanishka Jayasekara', 'kanishka.jayasekara7@healthsync.com', 'Psychiatry', 'Kandy General Hospital', 17, '+94-71-1125461', 'Wed-Fri, 9AM-4PM', 'CONSULTANT'),
('Dr. Dulaj Bandara', 'dulaj.bandara8@healthsync.com', 'Gynecology', 'Karapitiya Teaching Hospital', 1, '+94-76-1143384', 'Thu-Mon, 9AM-5PM', 'INTERN'),
('Dr. Sajith Rajapaksa', 'sajith.rajapaksa9@healthsync.com', 'ENT', 'Negombo General Hospital', 3, '+94-72-1161307', 'Fri-Tue, 9AM-3PM', 'MO'),
('Dr. Rohan Gunawardena', 'rohan.gunawardena10@healthsync.com', 'Cardiology', 'National Hospital of Sri Lanka', 5, '+94-70-1179230', 'Mon-Wed, 9AM-4PM', 'REGISTRAR'),
('Dr. Thilina Ranasinghe', 'thilina.ranasinghe11@healthsync.com', 'Pediatrics', 'Sri Jayewardenepura General Hospital', 21, '+94-11-1197153', 'Tue-Thu, 9AM-5PM', 'CONSULTANT'),
('Dr. Dilhara Wickramasinghe', 'dilhara.wickramasinghe12@healthsync.com', 'Neurology', 'Lanka Hospitals', 1, '+94-77-1215076', 'Wed-Fri, 9AM-3PM', 'INTERN'),
('Dr. Ishara Alwis', 'ishara.alwis13@healthsync.com', 'Dermatology', 'Durdans Hospital', 4, '+94-71-1232999', 'Thu-Mon, 9AM-4PM', 'MO'),
('Dr. Nimal Peiris', 'nimal.peiris14@healthsync.com', 'General Medicine', 'Nawaloka Hospital', 9, '+94-76-1250922', 'Fri-Tue, 9AM-5PM', 'REGISTRAR'),
('Dr. Sunil Cooray', 'sunil.cooray15@healthsync.com', 'Orthopedics', 'Asiri Surgical Hospital', 10, '+94-72-1268845', 'Mon-Wed, 9AM-3PM', 'CONSULTANT'),
('Dr. Kamal De Silva', 'kamal.de silva16@healthsync.com', 'Ophthalmology', 'Colombo General Hospital', 1, '+94-70-1286768', 'Tue-Thu, 9AM-4PM', 'INTERN'),
('Dr. Chathura Weerasinghe', 'chathura.weerasinghe17@healthsync.com', 'Psychiatry', 'Kandy General Hospital', 5, '+94-11-1304691', 'Wed-Fri, 9AM-5PM', 'MO'),
('Dr. Malith Liyanage', 'malith.liyanage18@healthsync.com', 'Gynecology', 'Karapitiya Teaching Hospital', 8, '+94-77-1322614', 'Thu-Mon, 9AM-3PM', 'REGISTRAR'),
('Dr. Harsha Mendis', 'harsha.mendis19@healthsync.com', 'ENT', 'Negombo General Hospital', 14, '+94-71-1340537', 'Fri-Tue, 9AM-4PM', 'CONSULTANT'),
('Dr. Asanka Rodrigo', 'asanka.rodrigo20@healthsync.com', 'Cardiology', 'National Hospital of Sri Lanka', 1, '+94-76-1358460', 'Mon-Wed, 9AM-5PM', 'INTERN'),
('Dr. Nuwan Goonetilleke', 'nuwan.goonetilleke21@healthsync.com', 'Pediatrics', 'Sri Jayewardenepura General Hospital', 3, '+94-72-1376383', 'Tue-Thu, 9AM-3PM', 'MO'),
('Dr. Roshan Samaranayake', 'roshan.samaranayake22@healthsync.com', 'Neurology', 'Lanka Hospitals', 7, '+94-70-1394306', 'Wed-Fri, 9AM-4PM', 'REGISTRAR'),
('Dr. Amara Karunaratne', 'amara.karunaratne23@healthsync.com', 'Dermatology', 'Durdans Hospital', 18, '+94-11-1412229', 'Thu-Mon, 9AM-5PM', 'CONSULTANT'),
('Dr. Shirani Jayawardene', 'shirani.jayawardene24@healthsync.com', 'General Medicine', 'Nawaloka Hospital', 1, '+94-77-1430152', 'Fri-Tue, 9AM-3PM', 'INTERN'),
('Dr. Malkanthi Dissanayake', 'malkanthi.dissanayake25@healthsync.com', 'Orthopedics', 'Asiri Surgical Hospital', 4, '+94-71-1448075', 'Mon-Wed, 9AM-4PM', 'MO'),
('Dr. Chitra Edirisinghe', 'chitra.edirisinghe26@healthsync.com', 'Ophthalmology', 'Colombo General Hospital', 6, '+94-76-1465998', 'Tue-Thu, 9AM-5PM', 'REGISTRAR'),
('Dr. Samanthi Attygalle', 'samanthi.attygalle27@healthsync.com', 'Psychiatry', 'Kandy General Hospital', 22, '+94-72-1483921', 'Wed-Fri, 9AM-3PM', 'CONSULTANT'),
('Dr. Deepika Hettiarachchi', 'deepika.hettiarachchi28@healthsync.com', 'Gynecology', 'Karapitiya Teaching Hospital', 1, '+94-70-1501844', 'Thu-Mon, 9AM-4PM', 'INTERN'),
('Dr. Priyanthi Premadasa', 'priyanthi.premadasa29@healthsync.com', 'ENT', 'Negombo General Hospital', 5, '+94-11-1519767', 'Fri-Tue, 9AM-5PM', 'MO'),
('Dr. Kanthi Amarasinghe', 'kanthi.amarasinghe30@healthsync.com', 'Cardiology', 'National Hospital of Sri Lanka', 5, '+94-77-1537690', 'Mon-Wed, 9AM-3PM', 'REGISTRAR'),
('Dr. Geeth Wickramasingha', 'geeth.wickramasingha31@healthsync.com', 'Pediatrics', 'Sri Jayewardenepura General Hospital', 11, '+94-71-1555613', 'Tue-Thu, 9AM-4PM', 'CONSULTANT'),
('Dr. Dinesh Ekanayake', 'dinesh.ekanayake32@healthsync.com', 'Neurology', 'Lanka Hospitals', 1, '+94-76-1573536', 'Wed-Fri, 9AM-5PM', 'INTERN'),
('Dr. Sanath Nanayakkara', 'sanath.nanayakkara33@healthsync.com', 'Dermatology', 'Durdans Hospital', 3, '+94-72-1591459', 'Thu-Mon, 9AM-3PM', 'MO'),
('Dr. Mahela Senaratne', 'mahela.senaratne34@healthsync.com', 'General Medicine', 'Nawaloka Hospital', 9, '+94-70-1609382', 'Fri-Tue, 9AM-4PM', 'REGISTRAR'),
('Dr. Kumar Kulasekara', 'kumar.kulasekara35@healthsync.com', 'Orthopedics', 'Asiri Surgical Hospital', 15, '+94-11-1627305', 'Mon-Wed, 9AM-5PM', 'CONSULTANT'),
('Dr. Lasith Herath', 'lasith.herath36@healthsync.com', 'Ophthalmology', 'Colombo General Hospital', 1, '+94-77-1645228', 'Tue-Thu, 9AM-3PM', 'INTERN'),
('Dr. Angelo Samarasinghe', 'angelo.samarasinghe37@healthsync.com', 'Psychiatry', 'Kandy General Hospital', 4, '+94-71-1663151', 'Wed-Fri, 9AM-4PM', 'MO'),
('Dr. Dimuth Jayasinghe', 'dimuth.jayasinghe38@healthsync.com', 'Gynecology', 'Karapitiya Teaching Hospital', 8, '+94-76-1681074', 'Thu-Mon, 9AM-5PM', 'REGISTRAR'),
('Dr. Pathum Chandrasiri', 'pathum.chandrasiri39@healthsync.com', 'ENT', 'Negombo General Hospital', 19, '+94-72-1698997', 'Fri-Tue, 9AM-3PM', 'CONSULTANT'),
('Dr. Wanindu Wijewardene', 'wanindu.wijewardene40@healthsync.com', 'Cardiology', 'National Hospital of Sri Lanka', 1, '+94-70-1716920', 'Mon-Wed, 9AM-4PM', 'INTERN'),
('Dr. Charith Perera', 'charith.perera41@healthsync.com', 'Pediatrics', 'Sri Jayewardenepura General Hospital', 5, '+94-11-1734843', 'Tue-Thu, 9AM-5PM', 'MO'),
('Dr. Bhanuka Senanayake', 'bhanuka.senanayake42@healthsync.com', 'Neurology', 'Lanka Hospitals', 7, '+94-77-1752766', 'Wed-Fri, 9AM-3PM', 'REGISTRAR'),
('Dr. Dushmantha Jayasundara', 'dushmantha.jayasundara43@healthsync.com', 'Dermatology', 'Durdans Hospital', 23, '+94-71-1770689', 'Thu-Mon, 9AM-4PM', 'CONSULTANT'),
('Dr. Lahiru Silva', 'lahiru.silva44@healthsync.com', 'General Medicine', 'Nawaloka Hospital', 1, '+94-76-1788612', 'Fri-Tue, 9AM-5PM', 'INTERN'),
('Dr. Kusal Fernando', 'kusal.fernando45@healthsync.com', 'Orthopedics', 'Asiri Surgical Hospital', 3, '+94-72-1806535', 'Mon-Wed, 9AM-3PM', 'MO'),
('Dr. Danushka Herath', 'danushka.herath46@healthsync.com', 'Ophthalmology', 'Colombo General Hospital', 6, '+94-70-1824458', 'Tue-Thu, 9AM-4PM', 'REGISTRAR'),
('Dr. Suranga Jayasekara', 'suranga.jayasekara47@healthsync.com', 'Psychiatry', 'Kandy General Hospital', 12, '+94-11-1842381', 'Wed-Fri, 9AM-5PM', 'CONSULTANT'),
('Dr. Dilruwan Bandara', 'dilruwan.bandara48@healthsync.com', 'Gynecology', 'Karapitiya Teaching Hospital', 1, '+94-77-1860304', 'Thu-Mon, 9AM-3PM', 'INTERN'),
('Dr. Milinda Rajapaksa', 'milinda.rajapaksa49@healthsync.com', 'ENT', 'Negombo General Hospital', 4, '+94-71-1878227', 'Fri-Tue, 9AM-4PM', 'MO');
